# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IntroUTIEswift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntroUTIEswift

pod 'IntroScreen'	


  target 'IntroUTIEswiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntroUTIEswiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
